[package]
name = "mpdiscord"
version = "0.1.0"
authors = ["leo60228 <leo@60228.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
async-thread = "0.1.2"
discord_game_sdk = "1.0.1"
mpd_client = "0.5.0"
once_cell = "1.5.2"
tokio = { version = "1.1.1", features = ["full"] }
